---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[metagenomics::_common]
      - recipe[chef-bioinf-worker::qiime]
      - recipe[chef-cuneiform::default]
      - recipe[metagenomics::default]
    attributes:
